### ISSUE TITLE
 Communication error - TimeoutException

### ISSUE THREAD

**Issue by emyasar** [minio/minio-jenkins#7]
I am getting TimeOutException - when i try to upload big size (+400MB) files. 

> ERROR: Communication error, failed to upload files
java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
	at com.squareup.okhttp.Call.getResponse(Call.java:287)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.minio.MinioClient.execute(MinioClient.java:826)
	at io.minio.MinioClient.executePut(MinioClient.java:1083)
	at io.minio.MinioClient.executePut(MinioClient.java:1106)
	at io.minio.MinioClient.putObject(MinioClient.java:2353)
	at io.minio.MinioClient.putObject(MinioClient.java:2423)
	at io.minio.MinioClient.putObject(MinioClient.java:2319)
	at org.jenkinsci.plugins.minio.MinioAllPathUploader.invoke(MinioAllPathUploader.java:100)
	at org.jenkinsci.plugins.minio.MinioAllPathUploader.invoke(MinioAllPathUploader.java:42)
	at hudson.FilePath.act(FilePath.java:998)
	at hudson.FilePath.act(FilePath.java:976)
	at org.jenkinsci.plugins.minio.MinioUploader.perform(MinioUploader.java:195)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$2.perform(BuildStepMonitor.java:32)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:735)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:676)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:621)
	at hudson.model.Run.execute(Run.java:1760)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 34 more

**Comment by nitisht** [comment]
Hello @emyasar can you please try this plugin file and let us know how it goes


[minio-storage.zip](https://github.com/minio/minio-jenkins/files/1251102/minio-storage.zip)

**Comment by nitisht** [comment]
As discussed with @emyasar on Slack. The solution works. We'll make a release with this fix soon.

**Comment by nitisht** [comment]
@emyasar just released the updated Minio Jenkins plugin 0.0.3 - https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/minio-storage/0.0.3/ with the fix. 


Thank you for reporting the issue.
